2024-12-22 16:24:40,005 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Даша\Desktop\обучение\pythonProject12+\.venv\tests_12_4\tests_12_4.py", line 23, in test_run
    runner = Runner(None)
  File "C:\Users\Даша\Desktop\обучение\pythonProject12+\.venv\tests_12_4\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано NoneType
2024-12-22 16:24:40,006 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Даша\Desktop\обучение\pythonProject12+\.venv\tests_12_4\tests_12_4.py", line 13, in test_walk
    runner = Runner("TestR", -5)
  File "C:\Users\Даша\Desktop\обучение\pythonProject12+\.venv\tests_12_4\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
